export * from "../Heros/pages/DcPage"
export * from "../Heros/pages/MarvelPage"
export * from "../Heros/pages/Hero"
export * from "../Heros/pages/Search"
export * from "../Heros/components/Navbar"
export * from "./routes/HerosRoutes"